apiVersion: v1
kind: DeploymentConfig
metadata:
  name: accountlocks
spec:
  replicas: 2
  selector:
    app: accountlocks
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: accountlocks
    spec:
      containers:
      - name: accountlocks
        image: us.icr.io/sisspace/accountlocks:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7800
          name: http
          protocol: TCP
        env:
        - name: LICENSE
          value: accept
