apiVersion: v1
kind: Service
metadata:
  name: accountlocks
  namespace: test-poc
spec:
  ports:
   - port: 7801
     name: restport
     protocol: TCP
     targetPort: 7800
   - port: 7802
     name: restadmin
     protocol: TCP
     targetPort: 7600
  selector:
    app: accountlocks
  type: ClusterIP
